# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.2
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: timothyogwulumba@gmail.com
author_name: Timothy Ogwulumba
contract_name: asset_market
preset_name: starter
project_name: asset-market

